spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://127.0.0.1:3306/portfolio?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: "0000"

#logging:
#  level:
#    org.springframework: info
#    com.iraefolio: debug
#    org.springframework.security: trace

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

